// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace liaison_donnees
{
	public partial class OutlineViewController : NSViewController
	{
		private NSMutableArray _people = new NSMutableArray();
		
		public OutlineViewController(IntPtr handle) : base(handle)
		{
		}
		
		[Export("personModelArray")]
		public NSArray People {
			get { return _people; }
		}
		
		[Export("addObject:")]
		public void AddPerson(PersonModel person) {
			WillChangeValue ("personModelArray");
			_people.Add (person);
			DidChangeValue ("personModelArray");
		}

		[Export("insertObject:inPersonModelArrayAtIndex:")]
		public void InsertPerson(PersonModel person, nint index) {
			WillChangeValue ("personModelArray");
			_people.Insert (person, index);
			DidChangeValue ("personModelArray");
		}

		[Export("removeObjectFromPersonModelArrayAtIndex:")]
		public void RemovePerson(nint index) {
			WillChangeValue ("personModelArray");
			_people.RemoveObject (index);
			DidChangeValue ("personModelArray");
		}

		[Export("setPersonModelArray:")]
		public void SetPeople(NSMutableArray array) {
			WillChangeValue ("personModelArray");
			_people = array;
			DidChangeValue ("personModelArray");
		}
		
		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			// Build list of employees
			var Craig = new PersonModel ("Craig Dunn", "Documentation Manager");
			Craig.AddPerson (new PersonModel ("Amy Burns", "Technical Writer"));
			Craig.AddPerson (new PersonModel ("Joel Martinez", "Web & Infrastructure"));
			Craig.AddPerson (new PersonModel ("Kevin Mullins", "Technical Writer"));
			Craig.AddPerson (new PersonModel ("Mark McLemore", "Technical Writer"));
			Craig.AddPerson (new PersonModel ("Tom Opgenorth", "Technical Writer"));
			AddPerson (Craig);

			var Larry = new PersonModel ("Larry O'Brien", "API Documentation Manager");
			Larry.AddPerson (new PersonModel ("Mike Norman", "API Documenter"));
			AddPerson (Larry);

		}
	}
}
