// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace liaison_donnees
{
	public partial class TableViewController : NSView
	{
		public TableViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
